o1= float(input("Enter a first operand: "))
o2= float(input("Enter a first operand: "))
op=input("Enter Operator +, -, %, /, ^, *: ")
if op=='+': print(o1+o2)
elif op=='-': print(o1-o2)
elif op=='%': print(o1%o2)
elif op=='/': print(o1/o2)
elif op=='^': print(o1^o2)
elif op=='*': print(o1*o2)
else: print("Invalid Operator!!")